### ISSUE TITLE
Cache helper does not work UWP apps

### ISSUE THREAD

**Issue by GabeDeBacker** [AzureAD/microsoft-authentication-extensions-for-dotnet#111]
I was super excited to try this out instead of doing my own serialization for my UWP app.

But it doesn't work due to code here:
https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/c23dd2c211f88143b583a3dd69e50cc55b8c7e43/src/Shared/SharedUtilities.cs

As it is trying to retrieve information about the OS en

Exception thrown: 'System.PlatformNotSupportedException' in System.Diagnostics.Process.dll
Retrieving information about local processes is not supported on this platform.

The documentation here:
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization

Isn't very clear about serialization for UWP apps.

It mentions "in-memory" followed "serialization by default". Does that mean that I don't need to serialize to disk for UWP apps (mine is running on a non-mobile platform).

That documentation also states that custom serialization isn't available for UWP, which is odd, because that's precisely what I'm currently doing :)

**Comment by jmprieur** [comment]
@GabeDeBacker : this extension library is mean for desktop applications (think, console, WPF, Windows.Forms). We have not tested it with UWP.

**Comment by bgavrilMS** [comment]
Yeah, we haven't tested on UWP. This is likely some obscure API that is available in netstandard but not in UWP ...

I am curious though, why would you need this on UWP? MSAL uses a DPAPI to store encrypted date in a file (or you can define your own serialization which is what you seem to be doing). This library does exactly what MSAL does - uses DPAPI + file on Windows.

I think the value proposition of this library is more around: 

- token cache encryption on Mac and Linux as well as Windows (not interesting for UWP)
- scenarios where multiple apps share the same token cache (I doubt this would work on UWP out of the box, since UWP is super locked down)
